package org.ratemycourse.GetCourses;

import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
@RequestMapping(path="/courses")
public class MainController {

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	
	
	
	
	
	private CourseRepository courseRepository;

	@RequestMapping(path="/add", method=RequestMethod.POST)
	public @ResponseBody String addNewCourse (@RequestParam(value="id") int id, 
			@RequestParam(value="name") String name, @RequestParam(value="school") String school, 
			@RequestParam(value="dept") String dept, @RequestParam(value="number") String number,
			@RequestParam(value="description") String description, @RequestParam(value="attrs") String attrs) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Course n = new Course();
		n.setId(id);
		n.setSchool(school);
		n.setDept(dept);
		n.setNumber(number);
		n.setAttrs(new String[] {attrs});
		n.setName(name);
		n.setDescription(description);

		courseRepository.save(n);
		return "Saved";
	}
	
	@RequestMapping(value = "/{courseId}", method = RequestMethod.GET)
	public @ResponseBody Optional<Course> getCourse(@PathVariable long courseId) {
		return courseRepository.findById(courseId);
	}
	
	@RequestMapping(path="/findDept", method=RequestMethod.GET)
	public @ResponseBody List<Course> getDepartment(@RequestParam(value="dept") String deptId) {
		return courseRepository.findByDept(deptId);
	}
	
	@RequestMapping(path="/findSchool", method=RequestMethod.GET)
	public @ResponseBody List<Course> getSchool(@RequestParam(value="school") String schoolId) {
		return courseRepository.findBySchool(schoolId);
	}
	
	@RequestMapping(path="/findSchoolAndDept", method = RequestMethod.GET)
	public @ResponseBody List<Course> getSchoolAndDepartment(@RequestParam(value="school") String schoolId, 
			@RequestParam(value="dept") String deptId) {
		return courseRepository.findBySchoolAndDept(schoolId, deptId);
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<Course> getAllCourses() {
		// returns JSON with the courses
		return courseRepository.findAll();
	}

}